# Generated by Django 2.2.19 on 2021-02-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Icono', models.CharField(default='', max_length=500)),
                ('Descripcion', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_En_Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(default='', max_length=200)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiene_iva', models.BooleanField()),
                ('Estado', models.CharField(max_length=50)),
                ('Categori_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Ciudad', models.IntegerField(default=4, editable=False)),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Logo', models.CharField(default='', max_length=500)),
                ('Stock_Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Stock_En_Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Ciudad', models.IntegerField(default=3, editable=False)),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Logo', models.CharField(default='', max_length=500)),
                ('Stock_Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Stock_En_Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Ciudad', models.IntegerField(default=2, editable=False)),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Logo', models.CharField(default='', max_length=500)),
                ('Stock_Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Stock_En_Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Ciudad', models.IntegerField(default=1, editable=False)),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Logo', models.CharField(default='', max_length=500)),
                ('Stock_Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Stock_En_Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Icono', models.CharField(default='', max_length=500)),
                ('Descripcion', models.CharField(default='', max_length=500)),
                ('ID_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=200)),
                ('Presentacion', models.CharField(default='', max_length=200)),
                ('Marca', models.CharField(default='', max_length=100)),
                ('Fabricante', models.CharField(default='', max_length=100)),
                ('Foto', models.CharField(default='', max_length=500)),
                ('Venta_al_granel', models.BooleanField(default=False)),
                ('Descripcion', models.TextField()),
                ('Nivel_Azucar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Nivel_Sal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Nivel_Grasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Estado', models.CharField(max_length=50)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Stock_En_Tienda')),
            ],
        ),
    ]
