# Generated by Django 2.2.19 on 2021-02-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210224_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda1',
            name='ID_Ciudad',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tienda2',
            name='ID_Ciudad',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tienda3',
            name='ID_Ciudad',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tienda4',
            name='ID_Ciudad',
            field=models.IntegerField(editable=False),
        ),
    ]
