# Generated by Django 2.2.19 on 2021-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20210224_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_en_tienda',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock_en_tienda',
            name='SKU',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tienda1',
            name='ID_Ciudad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tienda2',
            name='ID_Ciudad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tienda3',
            name='ID_Ciudad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tienda4',
            name='ID_Ciudad',
            field=models.IntegerField(),
        ),
    ]
